// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucsOlv/Turtwing_Back/ent/codeembedding"
	"github.com/LucsOlv/Turtwing_Back/ent/predicate"
	"github.com/LucsOlv/Turtwing_Back/ent/project"
	"github.com/google/uuid"
)

// CodeEmbeddingQuery is the builder for querying CodeEmbedding entities.
type CodeEmbeddingQuery struct {
	config
	ctx         *QueryContext
	order       []codeembedding.OrderOption
	inters      []Interceptor
	predicates  []predicate.CodeEmbedding
	withProject *ProjectQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CodeEmbeddingQuery builder.
func (ceq *CodeEmbeddingQuery) Where(ps ...predicate.CodeEmbedding) *CodeEmbeddingQuery {
	ceq.predicates = append(ceq.predicates, ps...)
	return ceq
}

// Limit the number of records to be returned by this query.
func (ceq *CodeEmbeddingQuery) Limit(limit int) *CodeEmbeddingQuery {
	ceq.ctx.Limit = &limit
	return ceq
}

// Offset to start from.
func (ceq *CodeEmbeddingQuery) Offset(offset int) *CodeEmbeddingQuery {
	ceq.ctx.Offset = &offset
	return ceq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ceq *CodeEmbeddingQuery) Unique(unique bool) *CodeEmbeddingQuery {
	ceq.ctx.Unique = &unique
	return ceq
}

// Order specifies how the records should be ordered.
func (ceq *CodeEmbeddingQuery) Order(o ...codeembedding.OrderOption) *CodeEmbeddingQuery {
	ceq.order = append(ceq.order, o...)
	return ceq
}

// QueryProject chains the current query on the "project" edge.
func (ceq *CodeEmbeddingQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: ceq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ceq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ceq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codeembedding.Table, codeembedding.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, codeembedding.ProjectTable, codeembedding.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(ceq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CodeEmbedding entity from the query.
// Returns a *NotFoundError when no CodeEmbedding was found.
func (ceq *CodeEmbeddingQuery) First(ctx context.Context) (*CodeEmbedding, error) {
	nodes, err := ceq.Limit(1).All(setContextOp(ctx, ceq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{codeembedding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ceq *CodeEmbeddingQuery) FirstX(ctx context.Context) *CodeEmbedding {
	node, err := ceq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CodeEmbedding ID from the query.
// Returns a *NotFoundError when no CodeEmbedding ID was found.
func (ceq *CodeEmbeddingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ceq.Limit(1).IDs(setContextOp(ctx, ceq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{codeembedding.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ceq *CodeEmbeddingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ceq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CodeEmbedding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CodeEmbedding entity is found.
// Returns a *NotFoundError when no CodeEmbedding entities are found.
func (ceq *CodeEmbeddingQuery) Only(ctx context.Context) (*CodeEmbedding, error) {
	nodes, err := ceq.Limit(2).All(setContextOp(ctx, ceq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{codeembedding.Label}
	default:
		return nil, &NotSingularError{codeembedding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ceq *CodeEmbeddingQuery) OnlyX(ctx context.Context) *CodeEmbedding {
	node, err := ceq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CodeEmbedding ID in the query.
// Returns a *NotSingularError when more than one CodeEmbedding ID is found.
// Returns a *NotFoundError when no entities are found.
func (ceq *CodeEmbeddingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ceq.Limit(2).IDs(setContextOp(ctx, ceq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{codeembedding.Label}
	default:
		err = &NotSingularError{codeembedding.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ceq *CodeEmbeddingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ceq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CodeEmbeddings.
func (ceq *CodeEmbeddingQuery) All(ctx context.Context) ([]*CodeEmbedding, error) {
	ctx = setContextOp(ctx, ceq.ctx, ent.OpQueryAll)
	if err := ceq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CodeEmbedding, *CodeEmbeddingQuery]()
	return withInterceptors[[]*CodeEmbedding](ctx, ceq, qr, ceq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ceq *CodeEmbeddingQuery) AllX(ctx context.Context) []*CodeEmbedding {
	nodes, err := ceq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CodeEmbedding IDs.
func (ceq *CodeEmbeddingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ceq.ctx.Unique == nil && ceq.path != nil {
		ceq.Unique(true)
	}
	ctx = setContextOp(ctx, ceq.ctx, ent.OpQueryIDs)
	if err = ceq.Select(codeembedding.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ceq *CodeEmbeddingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ceq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ceq *CodeEmbeddingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ceq.ctx, ent.OpQueryCount)
	if err := ceq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ceq, querierCount[*CodeEmbeddingQuery](), ceq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ceq *CodeEmbeddingQuery) CountX(ctx context.Context) int {
	count, err := ceq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ceq *CodeEmbeddingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ceq.ctx, ent.OpQueryExist)
	switch _, err := ceq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ceq *CodeEmbeddingQuery) ExistX(ctx context.Context) bool {
	exist, err := ceq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CodeEmbeddingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ceq *CodeEmbeddingQuery) Clone() *CodeEmbeddingQuery {
	if ceq == nil {
		return nil
	}
	return &CodeEmbeddingQuery{
		config:      ceq.config,
		ctx:         ceq.ctx.Clone(),
		order:       append([]codeembedding.OrderOption{}, ceq.order...),
		inters:      append([]Interceptor{}, ceq.inters...),
		predicates:  append([]predicate.CodeEmbedding{}, ceq.predicates...),
		withProject: ceq.withProject.Clone(),
		// clone intermediate query.
		sql:  ceq.sql.Clone(),
		path: ceq.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (ceq *CodeEmbeddingQuery) WithProject(opts ...func(*ProjectQuery)) *CodeEmbeddingQuery {
	query := (&ProjectClient{config: ceq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ceq.withProject = query
	return ceq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FileName string `json:"file_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CodeEmbedding.Query().
//		GroupBy(codeembedding.FieldFileName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ceq *CodeEmbeddingQuery) GroupBy(field string, fields ...string) *CodeEmbeddingGroupBy {
	ceq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CodeEmbeddingGroupBy{build: ceq}
	grbuild.flds = &ceq.ctx.Fields
	grbuild.label = codeembedding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FileName string `json:"file_name,omitempty"`
//	}
//
//	client.CodeEmbedding.Query().
//		Select(codeembedding.FieldFileName).
//		Scan(ctx, &v)
func (ceq *CodeEmbeddingQuery) Select(fields ...string) *CodeEmbeddingSelect {
	ceq.ctx.Fields = append(ceq.ctx.Fields, fields...)
	sbuild := &CodeEmbeddingSelect{CodeEmbeddingQuery: ceq}
	sbuild.label = codeembedding.Label
	sbuild.flds, sbuild.scan = &ceq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CodeEmbeddingSelect configured with the given aggregations.
func (ceq *CodeEmbeddingQuery) Aggregate(fns ...AggregateFunc) *CodeEmbeddingSelect {
	return ceq.Select().Aggregate(fns...)
}

func (ceq *CodeEmbeddingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ceq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ceq); err != nil {
				return err
			}
		}
	}
	for _, f := range ceq.ctx.Fields {
		if !codeembedding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ceq.path != nil {
		prev, err := ceq.path(ctx)
		if err != nil {
			return err
		}
		ceq.sql = prev
	}
	return nil
}

func (ceq *CodeEmbeddingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CodeEmbedding, error) {
	var (
		nodes       = []*CodeEmbedding{}
		_spec       = ceq.querySpec()
		loadedTypes = [1]bool{
			ceq.withProject != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CodeEmbedding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CodeEmbedding{config: ceq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ceq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ceq.withProject; query != nil {
		if err := ceq.loadProject(ctx, query, nodes, nil,
			func(n *CodeEmbedding, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ceq *CodeEmbeddingQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*CodeEmbedding, init func(*CodeEmbedding), assign func(*CodeEmbedding, *Project)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CodeEmbedding)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ceq *CodeEmbeddingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ceq.querySpec()
	_spec.Node.Columns = ceq.ctx.Fields
	if len(ceq.ctx.Fields) > 0 {
		_spec.Unique = ceq.ctx.Unique != nil && *ceq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ceq.driver, _spec)
}

func (ceq *CodeEmbeddingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(codeembedding.Table, codeembedding.Columns, sqlgraph.NewFieldSpec(codeembedding.FieldID, field.TypeUUID))
	_spec.From = ceq.sql
	if unique := ceq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ceq.path != nil {
		_spec.Unique = true
	}
	if fields := ceq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codeembedding.FieldID)
		for i := range fields {
			if fields[i] != codeembedding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ceq.withProject != nil {
			_spec.Node.AddColumnOnce(codeembedding.FieldProjectID)
		}
	}
	if ps := ceq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ceq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ceq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ceq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ceq *CodeEmbeddingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ceq.driver.Dialect())
	t1 := builder.Table(codeembedding.Table)
	columns := ceq.ctx.Fields
	if len(columns) == 0 {
		columns = codeembedding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ceq.sql != nil {
		selector = ceq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ceq.ctx.Unique != nil && *ceq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ceq.predicates {
		p(selector)
	}
	for _, p := range ceq.order {
		p(selector)
	}
	if offset := ceq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ceq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CodeEmbeddingGroupBy is the group-by builder for CodeEmbedding entities.
type CodeEmbeddingGroupBy struct {
	selector
	build *CodeEmbeddingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cegb *CodeEmbeddingGroupBy) Aggregate(fns ...AggregateFunc) *CodeEmbeddingGroupBy {
	cegb.fns = append(cegb.fns, fns...)
	return cegb
}

// Scan applies the selector query and scans the result into the given value.
func (cegb *CodeEmbeddingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cegb.build.ctx, ent.OpQueryGroupBy)
	if err := cegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CodeEmbeddingQuery, *CodeEmbeddingGroupBy](ctx, cegb.build, cegb, cegb.build.inters, v)
}

func (cegb *CodeEmbeddingGroupBy) sqlScan(ctx context.Context, root *CodeEmbeddingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cegb.fns))
	for _, fn := range cegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cegb.flds)+len(cegb.fns))
		for _, f := range *cegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CodeEmbeddingSelect is the builder for selecting fields of CodeEmbedding entities.
type CodeEmbeddingSelect struct {
	*CodeEmbeddingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ces *CodeEmbeddingSelect) Aggregate(fns ...AggregateFunc) *CodeEmbeddingSelect {
	ces.fns = append(ces.fns, fns...)
	return ces
}

// Scan applies the selector query and scans the result into the given value.
func (ces *CodeEmbeddingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ces.ctx, ent.OpQuerySelect)
	if err := ces.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CodeEmbeddingQuery, *CodeEmbeddingSelect](ctx, ces.CodeEmbeddingQuery, ces, ces.inters, v)
}

func (ces *CodeEmbeddingSelect) sqlScan(ctx context.Context, root *CodeEmbeddingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ces.fns))
	for _, fn := range ces.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ces.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ces.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
