// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucsOlv/Turtwing_Back/ent/codeembedding"
	"github.com/LucsOlv/Turtwing_Back/ent/predicate"
)

// CodeEmbeddingDelete is the builder for deleting a CodeEmbedding entity.
type CodeEmbeddingDelete struct {
	config
	hooks    []Hook
	mutation *CodeEmbeddingMutation
}

// Where appends a list predicates to the CodeEmbeddingDelete builder.
func (ced *CodeEmbeddingDelete) Where(ps ...predicate.CodeEmbedding) *CodeEmbeddingDelete {
	ced.mutation.Where(ps...)
	return ced
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ced *CodeEmbeddingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ced.sqlExec, ced.mutation, ced.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ced *CodeEmbeddingDelete) ExecX(ctx context.Context) int {
	n, err := ced.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ced *CodeEmbeddingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(codeembedding.Table, sqlgraph.NewFieldSpec(codeembedding.FieldID, field.TypeUUID))
	if ps := ced.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ced.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ced.mutation.done = true
	return affected, err
}

// CodeEmbeddingDeleteOne is the builder for deleting a single CodeEmbedding entity.
type CodeEmbeddingDeleteOne struct {
	ced *CodeEmbeddingDelete
}

// Where appends a list predicates to the CodeEmbeddingDelete builder.
func (cedo *CodeEmbeddingDeleteOne) Where(ps ...predicate.CodeEmbedding) *CodeEmbeddingDeleteOne {
	cedo.ced.mutation.Where(ps...)
	return cedo
}

// Exec executes the deletion query.
func (cedo *CodeEmbeddingDeleteOne) Exec(ctx context.Context) error {
	n, err := cedo.ced.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{codeembedding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cedo *CodeEmbeddingDeleteOne) ExecX(ctx context.Context) {
	if err := cedo.Exec(ctx); err != nil {
		panic(err)
	}
}
