// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucsOlv/Turtwing_Back/ent/history"
	"github.com/LucsOlv/Turtwing_Back/ent/historyproject"
	"github.com/LucsOlv/Turtwing_Back/ent/project"
	"github.com/google/uuid"
)

// HistoryProjectCreate is the builder for creating a HistoryProject entity.
type HistoryProjectCreate struct {
	config
	mutation *HistoryProjectMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (hpc *HistoryProjectCreate) SetProjectID(u uuid.UUID) *HistoryProjectCreate {
	hpc.mutation.SetProjectID(u)
	return hpc
}

// SetHistoryID sets the "history_id" field.
func (hpc *HistoryProjectCreate) SetHistoryID(u uuid.UUID) *HistoryProjectCreate {
	hpc.mutation.SetHistoryID(u)
	return hpc
}

// SetCreatedAt sets the "created_at" field.
func (hpc *HistoryProjectCreate) SetCreatedAt(t time.Time) *HistoryProjectCreate {
	hpc.mutation.SetCreatedAt(t)
	return hpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (hpc *HistoryProjectCreate) SetNillableCreatedAt(t *time.Time) *HistoryProjectCreate {
	if t != nil {
		hpc.SetCreatedAt(*t)
	}
	return hpc
}

// SetChanges sets the "changes" field.
func (hpc *HistoryProjectCreate) SetChanges(m map[string]interface{}) *HistoryProjectCreate {
	hpc.mutation.SetChanges(m)
	return hpc
}

// SetStatus sets the "status" field.
func (hpc *HistoryProjectCreate) SetStatus(h historyproject.Status) *HistoryProjectCreate {
	hpc.mutation.SetStatus(h)
	return hpc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (hpc *HistoryProjectCreate) SetNillableStatus(h *historyproject.Status) *HistoryProjectCreate {
	if h != nil {
		hpc.SetStatus(*h)
	}
	return hpc
}

// SetID sets the "id" field.
func (hpc *HistoryProjectCreate) SetID(u uuid.UUID) *HistoryProjectCreate {
	hpc.mutation.SetID(u)
	return hpc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (hpc *HistoryProjectCreate) SetNillableID(u *uuid.UUID) *HistoryProjectCreate {
	if u != nil {
		hpc.SetID(*u)
	}
	return hpc
}

// SetProject sets the "project" edge to the Project entity.
func (hpc *HistoryProjectCreate) SetProject(p *Project) *HistoryProjectCreate {
	return hpc.SetProjectID(p.ID)
}

// SetHistory sets the "history" edge to the History entity.
func (hpc *HistoryProjectCreate) SetHistory(h *History) *HistoryProjectCreate {
	return hpc.SetHistoryID(h.ID)
}

// Mutation returns the HistoryProjectMutation object of the builder.
func (hpc *HistoryProjectCreate) Mutation() *HistoryProjectMutation {
	return hpc.mutation
}

// Save creates the HistoryProject in the database.
func (hpc *HistoryProjectCreate) Save(ctx context.Context) (*HistoryProject, error) {
	hpc.defaults()
	return withHooks(ctx, hpc.sqlSave, hpc.mutation, hpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hpc *HistoryProjectCreate) SaveX(ctx context.Context) *HistoryProject {
	v, err := hpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hpc *HistoryProjectCreate) Exec(ctx context.Context) error {
	_, err := hpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hpc *HistoryProjectCreate) ExecX(ctx context.Context) {
	if err := hpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hpc *HistoryProjectCreate) defaults() {
	if _, ok := hpc.mutation.CreatedAt(); !ok {
		v := historyproject.DefaultCreatedAt()
		hpc.mutation.SetCreatedAt(v)
	}
	if _, ok := hpc.mutation.Changes(); !ok {
		v := historyproject.DefaultChanges
		hpc.mutation.SetChanges(v)
	}
	if _, ok := hpc.mutation.Status(); !ok {
		v := historyproject.DefaultStatus
		hpc.mutation.SetStatus(v)
	}
	if _, ok := hpc.mutation.ID(); !ok {
		v := historyproject.DefaultID()
		hpc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hpc *HistoryProjectCreate) check() error {
	if _, ok := hpc.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "HistoryProject.project_id"`)}
	}
	if _, ok := hpc.mutation.HistoryID(); !ok {
		return &ValidationError{Name: "history_id", err: errors.New(`ent: missing required field "HistoryProject.history_id"`)}
	}
	if _, ok := hpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HistoryProject.created_at"`)}
	}
	if _, ok := hpc.mutation.Changes(); !ok {
		return &ValidationError{Name: "changes", err: errors.New(`ent: missing required field "HistoryProject.changes"`)}
	}
	if _, ok := hpc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "HistoryProject.status"`)}
	}
	if v, ok := hpc.mutation.Status(); ok {
		if err := historyproject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HistoryProject.status": %w`, err)}
		}
	}
	if len(hpc.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "HistoryProject.project"`)}
	}
	if len(hpc.mutation.HistoryIDs()) == 0 {
		return &ValidationError{Name: "history", err: errors.New(`ent: missing required edge "HistoryProject.history"`)}
	}
	return nil
}

func (hpc *HistoryProjectCreate) sqlSave(ctx context.Context) (*HistoryProject, error) {
	if err := hpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	hpc.mutation.id = &_node.ID
	hpc.mutation.done = true
	return _node, nil
}

func (hpc *HistoryProjectCreate) createSpec() (*HistoryProject, *sqlgraph.CreateSpec) {
	var (
		_node = &HistoryProject{config: hpc.config}
		_spec = sqlgraph.NewCreateSpec(historyproject.Table, sqlgraph.NewFieldSpec(historyproject.FieldID, field.TypeUUID))
	)
	if id, ok := hpc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := hpc.mutation.CreatedAt(); ok {
		_spec.SetField(historyproject.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := hpc.mutation.Changes(); ok {
		_spec.SetField(historyproject.FieldChanges, field.TypeJSON, value)
		_node.Changes = value
	}
	if value, ok := hpc.mutation.Status(); ok {
		_spec.SetField(historyproject.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := hpc.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   historyproject.ProjectTable,
			Columns: []string{historyproject.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := hpc.mutation.HistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   historyproject.HistoryTable,
			Columns: []string{historyproject.HistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HistoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HistoryProjectCreateBulk is the builder for creating many HistoryProject entities in bulk.
type HistoryProjectCreateBulk struct {
	config
	err      error
	builders []*HistoryProjectCreate
}

// Save creates the HistoryProject entities in the database.
func (hpcb *HistoryProjectCreateBulk) Save(ctx context.Context) ([]*HistoryProject, error) {
	if hpcb.err != nil {
		return nil, hpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hpcb.builders))
	nodes := make([]*HistoryProject, len(hpcb.builders))
	mutators := make([]Mutator, len(hpcb.builders))
	for i := range hpcb.builders {
		func(i int, root context.Context) {
			builder := hpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HistoryProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hpcb *HistoryProjectCreateBulk) SaveX(ctx context.Context) []*HistoryProject {
	v, err := hpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hpcb *HistoryProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := hpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hpcb *HistoryProjectCreateBulk) ExecX(ctx context.Context) {
	if err := hpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
