// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucsOlv/Turtwing_Back/ent/history"
	"github.com/LucsOlv/Turtwing_Back/ent/historyproject"
	"github.com/LucsOlv/Turtwing_Back/ent/predicate"
	"github.com/LucsOlv/Turtwing_Back/ent/project"
	"github.com/LucsOlv/Turtwing_Back/ent/user"
	"github.com/google/uuid"
)

// HistoryUpdate is the builder for updating History entities.
type HistoryUpdate struct {
	config
	hooks    []Hook
	mutation *HistoryMutation
}

// Where appends a list predicates to the HistoryUpdate builder.
func (hu *HistoryUpdate) Where(ps ...predicate.History) *HistoryUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetUserID sets the "user_id" field.
func (hu *HistoryUpdate) SetUserID(u uuid.UUID) *HistoryUpdate {
	hu.mutation.SetUserID(u)
	return hu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (hu *HistoryUpdate) SetNillableUserID(u *uuid.UUID) *HistoryUpdate {
	if u != nil {
		hu.SetUserID(*u)
	}
	return hu
}

// SetProjectID sets the "project_id" field.
func (hu *HistoryUpdate) SetProjectID(u uuid.UUID) *HistoryUpdate {
	hu.mutation.SetProjectID(u)
	return hu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (hu *HistoryUpdate) SetNillableProjectID(u *uuid.UUID) *HistoryUpdate {
	if u != nil {
		hu.SetProjectID(*u)
	}
	return hu
}

// SetAction sets the "action" field.
func (hu *HistoryUpdate) SetAction(s string) *HistoryUpdate {
	hu.mutation.SetAction(s)
	return hu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (hu *HistoryUpdate) SetNillableAction(s *string) *HistoryUpdate {
	if s != nil {
		hu.SetAction(*s)
	}
	return hu
}

// SetDetails sets the "details" field.
func (hu *HistoryUpdate) SetDetails(m map[string]interface{}) *HistoryUpdate {
	hu.mutation.SetDetails(m)
	return hu
}

// SetIPAddress sets the "ip_address" field.
func (hu *HistoryUpdate) SetIPAddress(s string) *HistoryUpdate {
	hu.mutation.SetIPAddress(s)
	return hu
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (hu *HistoryUpdate) SetNillableIPAddress(s *string) *HistoryUpdate {
	if s != nil {
		hu.SetIPAddress(*s)
	}
	return hu
}

// ClearIPAddress clears the value of the "ip_address" field.
func (hu *HistoryUpdate) ClearIPAddress() *HistoryUpdate {
	hu.mutation.ClearIPAddress()
	return hu
}

// SetUser sets the "user" edge to the User entity.
func (hu *HistoryUpdate) SetUser(u *User) *HistoryUpdate {
	return hu.SetUserID(u.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (hu *HistoryUpdate) SetProject(p *Project) *HistoryUpdate {
	return hu.SetProjectID(p.ID)
}

// AddHistoryProjectIDs adds the "history_projects" edge to the HistoryProject entity by IDs.
func (hu *HistoryUpdate) AddHistoryProjectIDs(ids ...uuid.UUID) *HistoryUpdate {
	hu.mutation.AddHistoryProjectIDs(ids...)
	return hu
}

// AddHistoryProjects adds the "history_projects" edges to the HistoryProject entity.
func (hu *HistoryUpdate) AddHistoryProjects(h ...*HistoryProject) *HistoryUpdate {
	ids := make([]uuid.UUID, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hu.AddHistoryProjectIDs(ids...)
}

// Mutation returns the HistoryMutation object of the builder.
func (hu *HistoryUpdate) Mutation() *HistoryMutation {
	return hu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (hu *HistoryUpdate) ClearUser() *HistoryUpdate {
	hu.mutation.ClearUser()
	return hu
}

// ClearProject clears the "project" edge to the Project entity.
func (hu *HistoryUpdate) ClearProject() *HistoryUpdate {
	hu.mutation.ClearProject()
	return hu
}

// ClearHistoryProjects clears all "history_projects" edges to the HistoryProject entity.
func (hu *HistoryUpdate) ClearHistoryProjects() *HistoryUpdate {
	hu.mutation.ClearHistoryProjects()
	return hu
}

// RemoveHistoryProjectIDs removes the "history_projects" edge to HistoryProject entities by IDs.
func (hu *HistoryUpdate) RemoveHistoryProjectIDs(ids ...uuid.UUID) *HistoryUpdate {
	hu.mutation.RemoveHistoryProjectIDs(ids...)
	return hu
}

// RemoveHistoryProjects removes "history_projects" edges to HistoryProject entities.
func (hu *HistoryUpdate) RemoveHistoryProjects(h ...*HistoryProject) *HistoryUpdate {
	ids := make([]uuid.UUID, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hu.RemoveHistoryProjectIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HistoryUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HistoryUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hu *HistoryUpdate) check() error {
	if v, ok := hu.mutation.Action(); ok {
		if err := history.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "History.action": %w`, err)}
		}
	}
	if hu.mutation.UserCleared() && len(hu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "History.user"`)
	}
	if hu.mutation.ProjectCleared() && len(hu.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "History.project"`)
	}
	return nil
}

func (hu *HistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := hu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(history.Table, history.Columns, sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.Action(); ok {
		_spec.SetField(history.FieldAction, field.TypeString, value)
	}
	if value, ok := hu.mutation.Details(); ok {
		_spec.SetField(history.FieldDetails, field.TypeJSON, value)
	}
	if value, ok := hu.mutation.IPAddress(); ok {
		_spec.SetField(history.FieldIPAddress, field.TypeString, value)
	}
	if hu.mutation.IPAddressCleared() {
		_spec.ClearField(history.FieldIPAddress, field.TypeString)
	}
	if hu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.UserTable,
			Columns: []string{history.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.UserTable,
			Columns: []string{history.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if hu.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.ProjectTable,
			Columns: []string{history.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.ProjectTable,
			Columns: []string{history.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if hu.mutation.HistoryProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   history.HistoryProjectsTable,
			Columns: []string{history.HistoryProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(historyproject.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.RemovedHistoryProjectsIDs(); len(nodes) > 0 && !hu.mutation.HistoryProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   history.HistoryProjectsTable,
			Columns: []string{history.HistoryProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(historyproject.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.HistoryProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   history.HistoryProjectsTable,
			Columns: []string{history.HistoryProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(historyproject.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{history.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HistoryUpdateOne is the builder for updating a single History entity.
type HistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HistoryMutation
}

// SetUserID sets the "user_id" field.
func (huo *HistoryUpdateOne) SetUserID(u uuid.UUID) *HistoryUpdateOne {
	huo.mutation.SetUserID(u)
	return huo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (huo *HistoryUpdateOne) SetNillableUserID(u *uuid.UUID) *HistoryUpdateOne {
	if u != nil {
		huo.SetUserID(*u)
	}
	return huo
}

// SetProjectID sets the "project_id" field.
func (huo *HistoryUpdateOne) SetProjectID(u uuid.UUID) *HistoryUpdateOne {
	huo.mutation.SetProjectID(u)
	return huo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (huo *HistoryUpdateOne) SetNillableProjectID(u *uuid.UUID) *HistoryUpdateOne {
	if u != nil {
		huo.SetProjectID(*u)
	}
	return huo
}

// SetAction sets the "action" field.
func (huo *HistoryUpdateOne) SetAction(s string) *HistoryUpdateOne {
	huo.mutation.SetAction(s)
	return huo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (huo *HistoryUpdateOne) SetNillableAction(s *string) *HistoryUpdateOne {
	if s != nil {
		huo.SetAction(*s)
	}
	return huo
}

// SetDetails sets the "details" field.
func (huo *HistoryUpdateOne) SetDetails(m map[string]interface{}) *HistoryUpdateOne {
	huo.mutation.SetDetails(m)
	return huo
}

// SetIPAddress sets the "ip_address" field.
func (huo *HistoryUpdateOne) SetIPAddress(s string) *HistoryUpdateOne {
	huo.mutation.SetIPAddress(s)
	return huo
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (huo *HistoryUpdateOne) SetNillableIPAddress(s *string) *HistoryUpdateOne {
	if s != nil {
		huo.SetIPAddress(*s)
	}
	return huo
}

// ClearIPAddress clears the value of the "ip_address" field.
func (huo *HistoryUpdateOne) ClearIPAddress() *HistoryUpdateOne {
	huo.mutation.ClearIPAddress()
	return huo
}

// SetUser sets the "user" edge to the User entity.
func (huo *HistoryUpdateOne) SetUser(u *User) *HistoryUpdateOne {
	return huo.SetUserID(u.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (huo *HistoryUpdateOne) SetProject(p *Project) *HistoryUpdateOne {
	return huo.SetProjectID(p.ID)
}

// AddHistoryProjectIDs adds the "history_projects" edge to the HistoryProject entity by IDs.
func (huo *HistoryUpdateOne) AddHistoryProjectIDs(ids ...uuid.UUID) *HistoryUpdateOne {
	huo.mutation.AddHistoryProjectIDs(ids...)
	return huo
}

// AddHistoryProjects adds the "history_projects" edges to the HistoryProject entity.
func (huo *HistoryUpdateOne) AddHistoryProjects(h ...*HistoryProject) *HistoryUpdateOne {
	ids := make([]uuid.UUID, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return huo.AddHistoryProjectIDs(ids...)
}

// Mutation returns the HistoryMutation object of the builder.
func (huo *HistoryUpdateOne) Mutation() *HistoryMutation {
	return huo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (huo *HistoryUpdateOne) ClearUser() *HistoryUpdateOne {
	huo.mutation.ClearUser()
	return huo
}

// ClearProject clears the "project" edge to the Project entity.
func (huo *HistoryUpdateOne) ClearProject() *HistoryUpdateOne {
	huo.mutation.ClearProject()
	return huo
}

// ClearHistoryProjects clears all "history_projects" edges to the HistoryProject entity.
func (huo *HistoryUpdateOne) ClearHistoryProjects() *HistoryUpdateOne {
	huo.mutation.ClearHistoryProjects()
	return huo
}

// RemoveHistoryProjectIDs removes the "history_projects" edge to HistoryProject entities by IDs.
func (huo *HistoryUpdateOne) RemoveHistoryProjectIDs(ids ...uuid.UUID) *HistoryUpdateOne {
	huo.mutation.RemoveHistoryProjectIDs(ids...)
	return huo
}

// RemoveHistoryProjects removes "history_projects" edges to HistoryProject entities.
func (huo *HistoryUpdateOne) RemoveHistoryProjects(h ...*HistoryProject) *HistoryUpdateOne {
	ids := make([]uuid.UUID, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return huo.RemoveHistoryProjectIDs(ids...)
}

// Where appends a list predicates to the HistoryUpdate builder.
func (huo *HistoryUpdateOne) Where(ps ...predicate.History) *HistoryUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HistoryUpdateOne) Select(field string, fields ...string) *HistoryUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated History entity.
func (huo *HistoryUpdateOne) Save(ctx context.Context) (*History, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HistoryUpdateOne) SaveX(ctx context.Context) *History {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HistoryUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (huo *HistoryUpdateOne) check() error {
	if v, ok := huo.mutation.Action(); ok {
		if err := history.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "History.action": %w`, err)}
		}
	}
	if huo.mutation.UserCleared() && len(huo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "History.user"`)
	}
	if huo.mutation.ProjectCleared() && len(huo.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "History.project"`)
	}
	return nil
}

func (huo *HistoryUpdateOne) sqlSave(ctx context.Context) (_node *History, err error) {
	if err := huo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(history.Table, history.Columns, sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "History.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, history.FieldID)
		for _, f := range fields {
			if !history.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != history.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.Action(); ok {
		_spec.SetField(history.FieldAction, field.TypeString, value)
	}
	if value, ok := huo.mutation.Details(); ok {
		_spec.SetField(history.FieldDetails, field.TypeJSON, value)
	}
	if value, ok := huo.mutation.IPAddress(); ok {
		_spec.SetField(history.FieldIPAddress, field.TypeString, value)
	}
	if huo.mutation.IPAddressCleared() {
		_spec.ClearField(history.FieldIPAddress, field.TypeString)
	}
	if huo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.UserTable,
			Columns: []string{history.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.UserTable,
			Columns: []string{history.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if huo.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.ProjectTable,
			Columns: []string{history.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.ProjectTable,
			Columns: []string{history.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if huo.mutation.HistoryProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   history.HistoryProjectsTable,
			Columns: []string{history.HistoryProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(historyproject.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.RemovedHistoryProjectsIDs(); len(nodes) > 0 && !huo.mutation.HistoryProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   history.HistoryProjectsTable,
			Columns: []string{history.HistoryProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(historyproject.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.HistoryProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   history.HistoryProjectsTable,
			Columns: []string{history.HistoryProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(historyproject.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &History{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{history.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
