// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CodeEmbedding is the predicate function for codeembedding builders.
type CodeEmbedding func(*sql.Selector)

// History is the predicate function for history builders.
type History func(*sql.Selector)

// HistoryProject is the predicate function for historyproject builders.
type HistoryProject func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectMember is the predicate function for projectmember builders.
type ProjectMember func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
